# serverless.yml

service: invrtir-grafico-lineal-vista-previa
useDotEnv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: proy
  region: us-east-2
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    TABLE_CRIPTO: ${env:TABLE_CRIPTO}

functions:
  app:
    handler: index.handler
    name: grafico-lineal-vista-previa-app
    description: LCG8 - Obtiene el gráfico de vista previa de Precios Actuales de Criptos para la app desde los datos de AWS RDS.
    events:
      - http: GET /
      - http: 'GET {proxy+}'